"""Type stubs for minihost._core native extension module."""

from typing import Any, Callable, ClassVar, Union

import numpy as np
from numpy.typing import NDArray


# Audio inputs to process / write_audio / etc. accept any 2D float32
# c-contiguous buffer-protocol producer (AudioBuffer, numpy ndarray, and
# others via DLPack). The type alias documents the contract; at runtime
# the binding consumes whatever the buffer-protocol layer produces.
AudioInput = Union["AudioBuffer", NDArray[np.float32]]


class AudioBuffer:
    """Planar float32 audio buffer (stdlib-only; backed by juce::AudioBuffer)."""

    dtype: ClassVar[str]

    def __init__(self, channels: int, frames: int) -> None: ...
    @property
    def channels(self) -> int: ...
    @property
    def frames(self) -> int: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: tuple[Any, Any]) -> "float | AudioBuffer": ...
    def __setitem__(self, key: tuple[Any, Any], value: Any) -> None: ...
    def clear(self, start: int | None = None, count: int | None = None) -> None: ...
    def apply_gain(self, gain: float) -> None: ...
    def apply_gain_ramp(
        self, start: int, count: int, gain_start: float, gain_end: float
    ) -> None: ...
    def apply_gain_per_channel(self, gains: list[float]) -> None: ...
    def add_from(
        self,
        dest_channel: int,
        dest_start: int,
        source: "AudioBuffer",
        source_channel: int,
        source_start: int,
        count: int,
        gain: float = 1.0,
    ) -> None: ...
    def add_from_with_ramp(
        self,
        dest_channel: int,
        dest_start: int,
        source: "AudioBuffer",
        source_channel: int,
        source_start: int,
        count: int,
        gain_start: float,
        gain_end: float,
    ) -> None: ...
    def get_rms_level(
        self, channel: int, start: int = 0, count: int | None = None
    ) -> float: ...
    def reverse(
        self, start: int | None = None, count: int | None = None
    ) -> None: ...
    def reverse_channel(
        self, channel: int, start: int | None = None, count: int | None = None
    ) -> None: ...
    def magnitude(self, start: int | None = None, count: int | None = None) -> float: ...
    def copy(self) -> "AudioBuffer": ...
    def as_ndarray(self) -> NDArray[np.float32]: ...
    @classmethod
    def from_numpy(cls, array: Any) -> "AudioBuffer": ...
    def __array__(self, dtype: Any = None, copy: Any = None) -> NDArray[np.float32]: ...
    def __dlpack__(self, stream: Any = None) -> Any: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...


class Plugin:
    """Audio plugin wrapper for VST3 and AudioUnit plugins."""

    def __init__(
        self,
        path: str,
        sample_rate: float = 48000.0,
        max_block_size: int = 512,
        in_channels: int = 2,
        out_channels: int = 2,
        sidechain_channels: int = 0,
    ) -> None: ...
    @property
    def path(self) -> str: ...
    @property
    def num_params(self) -> int: ...
    @property
    def num_input_channels(self) -> int: ...
    @property
    def num_output_channels(self) -> int: ...
    @property
    def latency_samples(self) -> int: ...
    @property
    def tail_seconds(self) -> float: ...
    @property
    def sidechain_channels(self) -> int: ...
    @property
    def num_input_buses(self) -> int: ...
    @property
    def num_output_buses(self) -> int: ...
    @property
    def sample_rate(self) -> float: ...
    @sample_rate.setter
    def sample_rate(self, value: float) -> None: ...
    @property
    def num_programs(self) -> int: ...
    @property
    def program(self) -> int: ...
    @program.setter
    def program(self, value: int) -> None: ...
    @property
    def bypass(self) -> bool: ...
    @bypass.setter
    def bypass(self, value: bool) -> None: ...
    @property
    def non_realtime(self) -> bool: ...
    @non_realtime.setter
    def non_realtime(self, value: bool) -> None: ...
    @property
    def supports_double(self) -> bool: ...
    @property
    def accepts_midi(self) -> bool: ...
    @property
    def produces_midi(self) -> bool: ...
    @property
    def is_midi_effect(self) -> bool: ...
    @property
    def supports_mpe(self) -> bool: ...
    @property
    def processing_precision(self) -> int: ...
    @processing_precision.setter
    def processing_precision(self, value: int) -> None: ...
    def get_bus_info(self, is_input: bool, bus_index: int) -> dict[str, Any]: ...
    def check_buses_layout(
        self, input_channels: list[int], output_channels: list[int]
    ) -> bool: ...
    def begin_param_gesture(self, index: int) -> None: ...
    def end_param_gesture(self, index: int) -> None: ...
    def get_program_state(self) -> bytes: ...
    def set_program_state(self, data: bytes) -> None: ...
    def set_change_callback(self, callback: Any) -> None: ...
    def set_param_value_callback(self, callback: Any) -> None: ...
    def set_param_gesture_callback(self, callback: Any) -> None: ...
    def poll_callbacks(self) -> int: ...
    def callback_events_dropped(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Plugin": ...
    def __exit__(self, *args: object) -> None: ...
    def set_track_properties(
        self, name: str | None = None, colour: int | None = None
    ) -> None: ...
    def get_param(self, index: int) -> float: ...
    def set_param(self, index: int, value: float) -> None: ...
    def find_param(self, name: str) -> int: ...
    def get_param_by_name(self, name: str) -> float: ...
    def set_param_by_name(self, name: str, value: float) -> None: ...
    def get_param_info(self, index: int) -> dict[str, Any]: ...
    def param_to_text(self, index: int, value: float) -> str: ...
    def param_from_text(self, index: int, text: str) -> float: ...
    def get_program_name(self, index: int) -> str: ...
    def get_state(self) -> bytes: ...
    def set_state(self, data: bytes) -> None: ...
    def reset(self) -> None: ...
    def set_transport(
        self,
        bpm: float,
        time_sig_num: int = 4,
        time_sig_denom: int = 4,
        position_samples: int = 0,
        position_beats: float = 0.0,
        is_playing: bool = True,
        is_recording: bool = False,
        is_looping: bool = False,
        loop_start: int = 0,
        loop_end: int = 0,
    ) -> None: ...
    def clear_transport(self) -> None: ...
    def process(
        self,
        input: AudioInput,
        output: AudioInput,
    ) -> None: ...
    def process_midi(
        self,
        input: AudioInput,
        output: AudioInput,
        midi_in: list[tuple[int, int, int, int]],
    ) -> list[tuple[int, int, int, int]]: ...
    def process_auto(
        self,
        input: AudioInput,
        output: AudioInput,
        midi_in: list[tuple[int, int, int, int]],
        param_changes: list[tuple[int, int, float]],
    ) -> list[tuple[int, int, int, int]]: ...
    def process_sidechain(
        self,
        main_in: AudioInput,
        main_out: AudioInput,
        sidechain_in: AudioInput,
    ) -> None: ...
    def process_double(
        self,
        input: NDArray[np.float64],
        output: NDArray[np.float64],
    ) -> None: ...

class PluginChain:
    """Chain of audio plugins for sequential processing."""

    def __init__(self, plugins: list[Plugin]) -> None: ...
    @property
    def num_plugins(self) -> int: ...
    @property
    def latency_samples(self) -> int: ...
    @property
    def num_input_channels(self) -> int: ...
    @property
    def num_output_channels(self) -> int: ...
    @property
    def sample_rate(self) -> float: ...
    @property
    def tail_seconds(self) -> float: ...
    def get_plugin(self, index: int) -> Plugin: ...
    def set_mix(self, plugin_index: int, mix: float) -> None: ...
    def get_mix(self, plugin_index: int) -> float: ...
    def reset(self) -> None: ...
    def set_non_realtime(self, non_realtime: bool) -> None: ...
    def process(
        self,
        input: AudioInput,
        output: AudioInput,
    ) -> None: ...
    def process_midi(
        self,
        input: AudioInput,
        output: AudioInput,
        midi_in: list[tuple[int, int, int, int]],
    ) -> list[tuple[int, int, int, int]]: ...
    def process_auto(
        self,
        input: AudioInput,
        output: AudioInput,
        midi_in: list[tuple[int, int, int, int]],
        param_changes: list[tuple[int, int, int, float]],
    ) -> list[tuple[int, int, int, int]]: ...
    def close(self) -> None: ...
    def __enter__(self) -> "PluginChain": ...
    def __exit__(self, *args: object) -> None: ...

class PluginGraph:
    """Parallel-branches-summed plugin routing."""

    def __init__(
        self,
        num_in_channels: int,
        num_out_channels: int,
        max_block_size: int = 8192,
        sample_rate: float = 48000.0,
    ) -> None: ...
    def add_branch(self, chain: "PluginChain", gain: float = 1.0) -> int: ...
    def set_branch_gain(self, branch_index: int, gain: float) -> None: ...
    def get_branch_gain(self, branch_index: int) -> float: ...
    @property
    def num_branches(self) -> int: ...
    @property
    def num_input_channels(self) -> int: ...
    @property
    def num_output_channels(self) -> int: ...
    @property
    def sample_rate(self) -> float: ...
    @property
    def max_block_size(self) -> int: ...
    @property
    def latency_samples(self) -> int: ...
    @property
    def tail_seconds(self) -> float: ...
    def process(self, input: AudioInput, output: AudioInput) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> "PluginGraph": ...
    def __exit__(self, *args: object) -> None: ...

class Session:
    """Shared AudioPluginFormatManager across loads/probes/scans."""

    def __init__(self) -> None: ...
    def open(
        self,
        path: str,
        sample_rate: float = 48000.0,
        max_block_size: int = 512,
        in_channels: int = 2,
        out_channels: int = 2,
        sidechain_channels: int = 0,
    ) -> "Plugin": ...
    def probe(self, path: str) -> dict: ...
    def scan_directory(self, directory_path: str) -> list[dict]: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Session": ...
    def __exit__(self, *args: object) -> None: ...

class AudioDevice:
    """Real-time audio device for plugin playback."""

    def __init__(
        self,
        plugin: Plugin | PluginChain,
        sample_rate: float = 0.0,
        buffer_frames: int = 0,
        output_channels: int = 0,
        midi_input_port: int = -1,
        midi_output_port: int = -1,
        capture: bool = False,
        playback_device_index: int = -1,
        capture_device_index: int = -1,
    ) -> None: ...
    @property
    def is_playing(self) -> bool: ...
    @property
    def sample_rate(self) -> float: ...
    @property
    def buffer_frames(self) -> int: ...
    @property
    def channels(self) -> int: ...
    @property
    def midi_input_port(self) -> int: ...
    @property
    def midi_output_port(self) -> int: ...
    @property
    def is_midi_input_virtual(self) -> bool: ...
    @property
    def is_midi_output_virtual(self) -> bool: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def connect_midi_input(self, port_index: int) -> None: ...
    def connect_midi_output(self, port_index: int) -> None: ...
    def disconnect_midi_input(self) -> None: ...
    def disconnect_midi_output(self) -> None: ...
    def create_virtual_midi_input(self, port_name: str) -> None: ...
    def create_virtual_midi_output(self, port_name: str) -> None: ...
    def send_midi(self, status: int, data1: int, data2: int) -> None: ...
    def enable_input(self, capacity_frames: int = 0) -> None: ...
    def disable_input(self) -> None: ...
    def write_input(self, data: AudioInput) -> int: ...
    @property
    def input_available(self) -> int: ...
    def __enter__(self) -> "AudioDevice": ...
    def __exit__(self, *args: object) -> None: ...

class MidiFile:
    """MIDI file reader/writer."""

    def __init__(self) -> None: ...
    @property
    def num_tracks(self) -> int: ...
    @property
    def ticks_per_quarter(self) -> int: ...
    @ticks_per_quarter.setter
    def ticks_per_quarter(self, value: int) -> None: ...
    @property
    def duration_seconds(self) -> float: ...
    def load(self, path: str) -> bool: ...
    def save(self, path: str) -> bool: ...
    def add_track(self) -> int: ...
    def add_tempo(self, track: int, tick: int, bpm: float) -> None: ...
    def add_note_on(
        self, track: int, tick: int, channel: int, pitch: int, velocity: int
    ) -> None: ...
    def add_note_off(
        self, track: int, tick: int, channel: int, pitch: int, velocity: int = 0
    ) -> None: ...
    def add_control_change(
        self, track: int, tick: int, channel: int, controller: int, value: int
    ) -> None: ...
    def add_program_change(
        self, track: int, tick: int, channel: int, program: int
    ) -> None: ...
    def add_pitch_bend(
        self, track: int, tick: int, channel: int, value: int
    ) -> None: ...
    def get_events(self, track: int) -> list[dict[str, Any]]: ...
    def make_absolute_ticks(self) -> None: ...
    def make_delta_ticks(self) -> None: ...
    def join_tracks(self) -> None: ...
    def split_tracks(self) -> None: ...

class MidiIn:
    """Standalone MIDI input for monitoring MIDI messages."""

    @staticmethod
    def open(port_index: int, callback: Callable[[bytes], None]) -> "MidiIn": ...
    @staticmethod
    def open_virtual(name: str, callback: Callable[[bytes], None]) -> "MidiIn": ...
    def close(self) -> None: ...
    def __enter__(self) -> "MidiIn": ...
    def __exit__(self, *args: object) -> None: ...

def probe(path: str) -> dict[str, Any]:
    """Get plugin metadata without full instantiation."""
    ...

def scan_directory(directory_path: str) -> list[dict[str, Any]]:
    """Scan a directory for plugins (VST3, AudioUnit)."""
    ...

def midi_get_input_ports() -> list[dict[str, Any]]:
    """Get list of available MIDI input ports."""
    ...

def midi_get_output_ports() -> list[dict[str, Any]]:
    """Get list of available MIDI output ports."""
    ...

def audio_get_playback_devices() -> list[dict[str, Any]]:
    """Get list of available audio playback (output) devices.

    Each dict has: name (str), index (int), is_default (bool).
    """
    ...

def audio_get_capture_devices() -> list[dict[str, Any]]:
    """Get list of available audio capture (input) devices.

    Each dict has: name (str), index (int), is_default (bool).
    """
    ...

MH_CHANGE_LATENCY: int
MH_CHANGE_PARAM_INFO: int
MH_CHANGE_PROGRAM: int
MH_CHANGE_NON_PARAM_STATE: int
MH_PRECISION_SINGLE: int
MH_PRECISION_DOUBLE: int

# ABI version (mirrors header MH_API_VERSION_*).
MH_API_VERSION_MAJOR: int
MH_API_VERSION_MINOR: int
MH_API_VERSION_PATCH: int
MH_API_VERSION_NUMBER: int
MH_API_VERSION_STRING: str

def api_version() -> int:
    """Return the ABI version the linked C library was compiled against."""
    ...

def api_version_string() -> str:
    """Return the linked C library's ABI version as 'MAJOR.MINOR.PATCH'."""
    ...

def audio_read(path: str) -> tuple["AudioBuffer", int]:
    """Read an audio file. Returns (AudioBuffer, sample_rate) -- always AudioBuffer."""
    ...

def audio_write(
    path: str,
    data: AudioInput,
    sample_rate: int,
    bit_depth: int = 24,
) -> None:
    """Write audio data to a WAV file. Data shape: (channels, frames)."""
    ...

def audio_resample(
    data: AudioInput,
    sample_rate_in: int,
    sample_rate_out: int,
) -> "AudioBuffer":
    """Resample audio data. Returns AudioBuffer regardless of input type."""
    ...

def audio_get_file_info(path: str) -> dict[str, Any]:
    """Get audio file metadata without decoding."""
    ...

def vstpreset_read_class_id_from_bundle(vst3_path: str) -> str:
    """Read the processor class ID (32-char uppercase hex FUID) from a VST3 bundle."""
    ...

def vstpreset_read(path: str) -> tuple[str, bytes | None, bytes | None]:
    """Read a .vstpreset file via the C parser.

    Returns (class_id, component_state, controller_state). The latter two
    are bytes objects, or None if the corresponding chunk is absent.
    """
    ...

def vstpreset_write(
    path: str,
    class_id: str,
    component_state: bytes,
    controller_state: bytes | None = None,
) -> None:
    """Write a .vstpreset file via the C writer."""
    ...
